# Generated by Django 5.1.4 on 2025-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="purchase",
            field=models.BooleanField(default=False),
        ),
    ]
