# Generated by Django 5.1.4 on 2025-05-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_phases(apps, schema_editor):
    ServiceOrderPhase = apps.get_model("service_control", "ServiceOrderPhase")
    phase_names = ["PENDENTE", "FINALIZADO", "ATRASADO", "CONCLUÍDO", "RECUSADA"]
    for name in phase_names:
        ServiceOrderPhase.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_address_personsadresses_cep_and_more"),
        ("service_control", "0002_serviceorder_purchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="attendant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendant_service_orders",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_service_orders",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="payment_method",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ServiceOrderPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(blank=True, null=True)),
                ("date_canceled", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canceled_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="service_order_phase",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service_control.serviceorderphase",
            ),
        ),
        migrations.RunPython(create_initial_phases),
    ]
