# Generated by Django 5.1.4 on 2025-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_control",
            "0003_serviceorder_attendant_serviceorder_employee_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceorder",
            name="advance_payment",
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="renter_role",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="adjustment_needed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="remaining_payment",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="total_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
