# Generated by Django 5.1.4 on 2025-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0004_remove_serviceorder_advance_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="came_from",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
