# Generated by Django 5.1.4 on 2025-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0005_serviceorder_came_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="max_payment_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
