# Generated by Django 5.1.4 on 2025-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0006_serviceorder_max_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="justification_refusal",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
