# Generated by Django 5.1.4 on 2025-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0007_serviceorder_justification_refusal"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="advance_payment",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="devolucao_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="prova_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="retirada_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
