# Generated by Django 5.1.4 on 2025-07-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_temporaryproduct_brand_temporaryproduct_fabric"),
        ("service_control", "0008_serviceorder_advance_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items_color",
                to="products.color",
            ),
        ),
    ]
