# Generated by Django 5.1.4 on 2025-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0009_serviceorderitem_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="service_type",
            field=models.CharField(
                blank=True,
                help_text="Tipo de serviço (Aluguel, Compra, Aluguel + Venda)",
                max_length=50,
                null=True,
            ),
        ),
    ]
