# Generated by Django 5.1.4 on 2025-09-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0016_event_eventparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_orders",
                to="service_control.event",
            ),
        ),
    ]
