# Generated by Django 5.1.4 on 2025-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0017_serviceorder_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(blank=True, help_text="Data do evento", null=True),
        ),
    ]
