# Generated by Django 5.1.4 on 2025-09-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0018_event_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceorder",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="serviceorder",
            name="occasion",
        ),
    ]
