# Generated by Django 4.2.11 on 2025-11-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0023_add_esta_atrasada_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='production_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a OS foi movida para produção', null=True),
        ),
    ]
