# Generated by Django 4.2.11 on 2025-11-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0024_add_production_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='production_date',
            field=models.DateField(blank=True, help_text='Data em que a OS foi movida para produção', null=True),
        ),
    ]
