# Generated by Django 4.2.11 on 2025-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0027_add_data_recusa_data_finalizado_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='payment_details',
            field=models.JSONField(blank=True, help_text='Detalhes dos pagamentos [{amount, forma_pagamento}]', null=True),
        ),
    ]
