# Generated by Django 4.2.11 on 2025-11-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_control', '0028_add_payment_details_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='OS virtual apenas para registro de pagamento'),
        ),
    ]
