# Generated by Django 4.2.11 on 2025-11-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personsadresses_complemento'),
        ('service_control', '0029_add_is_virtual_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='accounts.person'),
        ),
    ]
