# Generated by Django 5.1.4 on 2025-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_populate_initial_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personsadresses",
            old_name="address",
            new_name="cep",
        ),
        migrations.AddField(
            model_name="personsadresses",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personsadresses",
            name="street",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
