# Generated by Django 5.1.4 on 2025-07-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_create_initial_admin_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personscontacts",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="accounts.person",
            ),
        ),
    ]
