# Generated by Django 5.1.4 on 2025-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_personscontacts_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="personsadresses",
            name="complemento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
