# Generated by Django 4.2.11 on 2026-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personsadresses_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personscontacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
