# Generated by Django 4.2.11 on 2026-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_email_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsadresses',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personsadresses',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personsadresses',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personscontacts',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
