# Generated by Django 5.1.4 on 2025-04-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_load_products_sql"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(blank=True, null=True)),
                ("date_canceled", models.DateTimeField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Paleto", "Paletó"),
                            ("Calca", "Calça"),
                            ("Camisa", "Camisa"),
                            ("Colete", "Colete"),
                            ("Gravata", "Gravata"),
                            ("Sapato", "Sapato"),
                            ("Suspensorio", "Suspensório"),
                            ("Cinto", "Cinto"),
                            ("Lenco", "Lenço"),
                        ],
                        max_length=20,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sleeve_length",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("leg_length", models.CharField(blank=True, max_length=10, null=True)),
                ("waist_size", models.CharField(blank=True, max_length=10, null=True)),
                ("collar_size", models.CharField(blank=True, max_length=10, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canceled_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "temporary_products",
            },
        ),
    ]
