# Generated by Django 5.1.4 on 2025-05-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_temporaryproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="temporaryproduct",
            name="fabric",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
