# Generated by Django 5.1.4 on 2025-07-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_temporaryproduct_brand_temporaryproduct_fabric"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryproduct",
            name="extensor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="temporaryproduct",
            name="extras",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="temporaryproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("paleto", "Paletó"),
                    ("calca", "Calça"),
                    ("camisa", "Camisa"),
                    ("colete", "Colete"),
                    ("gravata", "Gravata"),
                    ("sapato", "Sapato"),
                    ("suspensorio", "Suspensório"),
                    ("cinto", "Cinto"),
                    ("lenco", "Lenço"),
                    ("passante", "Passante"),
                ],
                max_length=20,
            ),
        ),
    ]
