# Generated by Django 5.1.4 on 2025-07-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_temporaryproduct_extensor_temporaryproduct_extras_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryproduct",
            name="venda",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indica se o item foi vendido",
                null=True,
            ),
        ),
    ]
