# Generated by Django 5.1.4 on 2025-08-06 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_temporaryproduct_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="botoes",
            field=models.CharField(
                blank=True,
                help_text="Tipo de botões (Um, Duplo)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cor",
            field=models.CharField(
                default="", help_text="Cor principal do produto", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="foto_base64",
            field=models.TextField(
                blank=True, help_text="Foto do produto em base64", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="id_produto",
            field=models.CharField(
                default="",
                help_text="ID único do produto (ex: P000001)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="intensidade_cor",
            field=models.CharField(
                default="",
                help_text="Intensidade da cor (Fosco, Acetinado)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lapela",
            field=models.CharField(
                blank=True,
                help_text="Tipo de lapela (Bico, Shale)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="marca",
            field=models.CharField(
                default="", help_text="Marca/fabricante do produto", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(
                default="", help_text="Composição do material", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="nome_produto",
            field=models.CharField(
                default="", help_text="Nome descritivo do produto", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="padronagem",
            field=models.CharField(
                default="", help_text="Padrão do tecido", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tamanho",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tamanho numérico",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tipo",
            field=models.CharField(
                default="",
                help_text="Tipo do produto (Paletó, Calça, Colete)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_by_brand",
                to="products.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_by_color",
                to="products.color",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_by_fabric",
                to="products.fabric",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.producttype",
            ),
        ),
    ]
