# Generated by Django 5.1.4 on 2025-08-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_botoes_product_cor_product_foto_base64_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="button",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fabric",
        ),
        migrations.RemoveField(
            model_name="product",
            name="label_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="lapel",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model",
        ),
        migrations.RemoveField(
            model_name="product",
            name="on_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pattern",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
    ]
