# Generated by Django 5.1.4 on 2025-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_brand_remove_product_button_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryproduct",
            name="ajuste_cintura",
            field=models.CharField(
                blank=True,
                help_text="Ajuste específico da cintura",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="temporaryproduct",
            name="ajuste_comprimento",
            field=models.CharField(
                blank=True,
                help_text="Ajuste específico do comprimento",
                max_length=255,
                null=True,
            ),
        ),
    ]
