# Generated by Django 4.2.11 on 2025-12-11 11:42

from django.db import migrations


def create_sem_marca_brand(apps, schema_editor):
    Brand = apps.get_model('products', 'Brand')
    Brand.objects.get_or_create(description='SEM MARCA')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_temporaryproduct_ajuste_cintura_and_more'),
    ]

    operations = [
        migrations.RunPython(create_sem_marca_brand),
    ]
